// 微信小游戏入口：使用 assets 中的图片素材，避免中文文件名和网页端 Vite 入口差异。
const canvas=wx.createCanvas(),ctx=canvas.getContext('2d');const W=canvas.width=375,H=canvas.height=667;
const skillNames={global_eat:'全屏吞噬',type_eat:'同类吞噬',speed_up:'极速冲刺',grow:'巨型成长',heal:'生命恢复',invincible:'无敌护盾'};
// 云开发环境 ID：在微信开发者工具“云开发”面板顶部复制，不是 AppID。
const CLOUD_ENV_ID='请替换为你的云环境ID';
if(wx.cloud&&CLOUD_ENV_ID.indexOf('请替换')!==0)wx.cloud.init({env:CLOUD_ENV_ID});
// 图片优先读取项目内 assets 目录，避免小游戏运行环境访问外部 CDN 超时。
// assets 目录随小游戏一起上传，不依赖浏览器代理、DNS 或 HTTP/2。
const LOCAL_ASSET_BASE='assets/';
// 仅作为显式开启时的备用地址；默认关闭，避免启动时产生外网请求。
const REMOTE_ASSET_BASE='https://raw.githubusercontent.com/longqingxuexin/fish_game/main/public/img/';
const USE_REMOTE_ASSET_FALLBACK=false;
const ASSET_FILES={};
const CLOUD_ASSET_FILES={
  // 示例：bg0:'cloud://环境ID.存储桶ID/鱼游戏/bg0.png'
};
const imageCache={};
const imageState={};
const downloadedAssets={};
const ASSET_NAMES=[...['bg0','bg1','bg2','bg3'],...['fish_small_1','fish_small_2','fish_small_3','fish_small_4','fish_small_5'],...['fish_big_6','fish_big_7','fish_big_8','fish_big_9'],...['fish_boss_1','fish_boss_10','fish_boss_11','fish_boss_12'],...['player_0','player_1','player_2','player_3','player_4'],...['fx_global'],...[1,2,3,4].map(n=>`fx_type_${n}`),...[1,2,3,4].map(n=>`fx_speed_${n}`),...[1,2,3,4].map(n=>`fx_grow_${n}`),...[1,2,3].map(n=>`fx_heal_${n}`),...[1,2].map(n=>`fx_shield_${n}`)];
const downloadAsset=(name,attempt=0)=>new Promise(resolve=>{const fileId=CLOUD_ASSET_FILES[name],url=fileId||`${REMOTE_ASSET_BASE}${name}.png`,done=(r)=>{if(r.statusCode===200){downloadedAssets[name]=r.tempFilePath;imageState[name]='loaded';resolve(true)}else if(attempt<2)setTimeout(()=>resolve(downloadAsset(name,attempt+1)),300);else{imageState[name]='failed';resolve(false)}},fail=e=>{if(attempt<2)setTimeout(()=>resolve(downloadAsset(name,attempt+1)),300);else{imageState[name]='failed';console.warn('图片下载失败',name,e);resolve(false)}};if(fileId&&wx.cloud)wx.cloud.downloadFile({fileID:fileId}).then(r=>done({statusCode:200,tempFilePath:r.tempFilePath})).catch(fail);else wx.downloadFile({url,success:done,fail})});
const preloadAssets=()=>Promise.all(ASSET_NAMES.map(n=>{imageState[n]='loading';return downloadAsset(n)}));
const img=n=>{const i=wx.createImage();imageCache[n]=i;imageState[n]=imageState[n]||'loading';i.onload=()=>{imageState[n]='loaded'};i.onerror=e=>{imageState[n]='failed';console.warn('图片使用失败，使用绘制fallback',n,e)};i.src=downloadedAssets[n]||`${REMOTE_ASSET_BASE}${n}.png`;return i};
let bg,small,big,boss,playerImgs,fx;
const initImages=()=>{bg=[0,1,2,3].map(n=>img(`bg${n}`));small=[1,2,3,4,5].map(n=>img(`fish_small_${n}`));big=[6,7,8,9].map(n=>img(`fish_big_${n}`));boss=[1,10,11,12].map(n=>img(`fish_boss_${n}`));playerImgs=[0,1,2,3,4].map(n=>img(`player_${n}`));fx={global_eat:[img('fx_global')],type_eat:[1,2,3,4].map(n=>img(`fx_type_${n}`)),speed_up:[1,2,3,4].map(n=>img(`fx_speed_${n}`)),grow:[1,2,3,4].map(n=>img(`fx_grow_${n}`)),heal:[1,2,3].map(n=>img(`fx_heal_${n}`)),invincible:[1,2].map(n=>img(`fx_shield_${n}`))}};
const rand=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);let player,fishes,skill,effect,particles,score,health,last,running,bgIndex=0,nextSkillAt,startedAt,growthXp,growthLevel,bossSpawned;
function viewScale(){return Math.min(1,(W*.20)/(player.size*2))}function displaySize(s){return Math.max(3,s*viewScale())}
function makeFish(forceSize=0,isBoss=false){const min=Math.max(1,player.size*.1-1),max=Math.max(min+1,player.size*1.1),size=forceSize||rand(min,max);return{x:rand(12,W-12),y:rand(100,H-14),size,kind:Math.floor(rand(0,5)),dx:Math.random()<.5?-1:1,dy:rand(-.35,.35),speed:isBoss?rand(10,18):rand(28,68),phase:Math.random()*Math.PI*2,turn:0,isBoss}}
function reset(){player={x:W/2,y:H/2,size:20,targetX:W/2,targetY:H/2};fishes=Array.from({length:24},makeFish);skill=null;effect=null;particles=[];score=0;health=3;growthXp=0;growthLevel=0;bossSpawned=false;startedAt=Date.now();running=true;nextSkillAt=Date.now()+30000;bgIndex=(bgIndex+1)%bg.length}
function burst(color,count=18){for(let i=0;i<count;i++)particles.push({x:player.x,y:player.y,dx:rand(-130,130),dy:rand(-130,130),life:1,color})}
function spawnSkill(){const types=Object.keys(skillNames);skill={x:rand(35,W-35),y:rand(120,H-50),size:20,type:types[Math.floor(rand(0,types.length))]}}
function startSkill(){const type=skill.type;const durations={global_eat:4,type_eat:3,speed_up:3,grow:2,heal:2,invincible:4};effect={type,started:Date.now(),until:Date.now()+durations[type]*1000,acc:0};skill=null;burst(type==='heal'?'#7dff9b':'#ffe66d',35);if(type==='grow')player.size+=player.size*.18;if(type==='heal')health=Math.min(3,health+1)}
function eatFish(i){const f=fishes[i];const ratio=f.size/player.size;const xp=ratio>=.82?3.2:ratio>=.58?2:ratio>=.35?1:.45;growthXp+=xp;score+=Math.round(f.size*10);const threshold=8+growthLevel*4;if(growthLevel<4&&growthXp>=threshold){growthXp-=threshold;growthLevel++;player.size=Math.min(92,player.size+6+growthLevel*2);burst('#ffe66d',24)}else{player.size=Math.min(92,player.size+Math.min(2.4,Math.max(.25,f.size/player.size*1.4)))}fishes.splice(i,1);fishes.push(makeFish());burst('#fff',5)}
function maybeSpawnBoss(){if(bossSpawned||Date.now()-startedAt<300000&&growthLevel<4)return;bossSpawned=true;const bossSize=Math.max(78,player.size*1.28);fishes.push(makeFish(bossSize,true));}
function activeEat(dt){if(!effect)return;effect.acc+=dt;if(effect.acc<.12)return;effect.acc=0;const radius=effect.type==='global_eat'?240:effect.type==='type_eat'?130:70;for(let i=fishes.length-1;i>=0;i--){const f=fishes[i],same=effect.type!=='type_eat'||f.kind===Math.floor(player.size)%5;if(dist(player,f)<radius&&f.size<=player.size&&same)eatFish(i)}}
function update(dt){const speed=effect?.type==='speed_up'?420:360,dx=player.targetX-player.x,dy=player.targetY-player.y,d=Math.hypot(dx,dy)||1;player.x+=dx*Math.min(1,dt*18);player.y+=dy*Math.min(1,dt*18);if(d>3){player.dx=dx/d;player.dy=dy/d}fishes.forEach(f=>{f.x+=f.dx*f.speed*dt;f.y+=f.dy*f.speed*dt;f.phase+=dt*(4+f.speed*.04);f.turn+=dt;if(f.turn>rand(.8,1.8)){f.dy=rand(-.3,.3);f.turn=0}if(f.x<-50||f.x>W+50)f.dx*=-1;if(f.y<85||f.y>H-8)f.dy*=-1});maybeSpawnBoss();for(let i=fishes.length-1;i>=0;i--){const f=fishes[i];if(dist(player,f)<displaySize(player.size)+displaySize(f.size)){if(player.size>=f.size)eatFish(i);else if(f.size>player.size*1.05&&effect?.type!=='invincible'){health--;fishes.splice(i,1);fishes.push(makeFish());if(health<=0)running=false}}}if(!skill&&Date.now()>=nextSkillAt){spawnSkill();nextSkillAt=Date.now()+30000}if(skill&&dist(player,skill)<displaySize(player.size)+skill.size)startSkill();if(effect){activeEat(dt);if(Date.now()>=effect.until)effect=null}particles.forEach(p=>{p.x+=p.dx*dt;p.y+=p.dy*dt;p.life-=dt*1.7});particles=particles.filter(p=>p.life>0)}
function drawFallback(x,y,w,h,color='#55cbe8',r=0){ctx.save();ctx.translate(x,y);ctx.rotate(r);ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(0,0,w*.36,h*.22,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-w*.25,0);ctx.lineTo(-w*.52,-h*.25);ctx.lineTo(-w*.52,h*.25);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(w*.18,-h*.06,Math.max(2,w*.035),0,Math.PI*2);ctx.fill();ctx.restore()}
function drawImg(i,x,y,w,h,a=1,r=0){if(!i||!i.width){drawFallback(x,y,w,h,'#55cbe8',r);return}ctx.save();ctx.globalAlpha=a;ctx.translate(x,y);ctx.rotate(r);ctx.drawImage(i,-w/2,-h/2,w,h);ctx.restore()}
function drawFish(f,isPlayer=false){const s=displaySize(f.size)*2.3,arr=isPlayer?playerImgs:f.isBoss?boss:f.size>48?big:small,i=arr[isPlayer?Math.min(4,Math.floor(player.size/22)):f.kind%arr.length],angle=(f.dy||0)*.18+Math.sin(f.phase||0)*.025;ctx.save();ctx.translate(f.x,f.y+Math.sin(f.phase||0)*1.2);if(f.dx<0&&!isPlayer)ctx.scale(-1,1);drawImg(i,0,0,s,s,1,angle);ctx.restore();ctx.fillStyle=f.isBoss?'#ffe66d':'#fff';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText(Math.round(f.size),f.x,f.y-s*.46);ctx.textAlign='left'}
function draw(){drawImg(bg[bgIndex],W/2,H/2,W,H);ctx.fillStyle='rgba(1,20,42,.82)';ctx.fillRect(0,0,W,76);ctx.fillStyle='#eaffff';ctx.font='bold 18px sans-serif';ctx.fillText('深海吞噬者',16,29);ctx.font='14px sans-serif';ctx.fillText(`分数 ${score} 生命 ${health} 体型 ${Math.round(player.size)} 成长 ${growthLevel}/4`,16,54);fishes.forEach(f=>drawFish(f));if(skill){drawImg(fx[skill.type][0],skill.x,skill.y,skill.size*4,skill.size*4,.9,Date.now()/1000);ctx.fillStyle='#fff';ctx.fillText(skillNames[skill.type],skill.x-24,skill.y+35)}particles.forEach(p=>{ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1});drawFish(player,true);if(effect){const frames=fx[effect.type],frame=Math.floor(Date.now()/100)%frames.length,s=displaySize(player.size)*3;drawImg(frames[frame],player.x,player.y,s,s,.75,Date.now()/2600);for(let i=0;i<8;i++){const a=Date.now()/700+i*.785,r=displaySize(player.size)*1.8;ctx.fillStyle='#fff0a0';ctx.beginPath();ctx.arc(player.x+Math.cos(a)*r,player.y+Math.sin(a)*r,3,0,Math.PI*2);ctx.fill()}}if(!running){ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 30px sans-serif';ctx.fillText('游戏结束',W/2,H/2);ctx.textAlign='left'}}
function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(running)update(dt);draw();requestAnimationFrame(loop)}
wx.onTouchStart(e=>{const t=e.touches[0];if(!running){reset();return}player.targetX=t.clientX;player.targetY=t.clientY});wx.onTouchMove(e=>{const t=e.touches[0];player.targetX=Math.max(8,Math.min(W-8,t.clientX));player.targetY=Math.max(85,Math.min(H-8,t.clientY))});
// 先下载到微信临时文件，再创建图片对象，避免把图片放进小游戏安装包。
preloadAssets().then(()=>{initImages();reset();requestAnimationFrame(now=>{last=now;loop(now)})});
