// 微信小游戏入口：使用 assets 中的图片素材，避免中文文件名和网页端 Vite 入口差异。
const canvas=wx.createCanvas(),ctx=canvas.getContext('2d');const W=canvas.width=375,H=canvas.height=667;
const skillNames={global_eat:'全屏吞噬',type_eat:'同类吞噬',speed_up:'极速冲刺',grow:'巨型成长',heal:'生命恢复',invincible:'无敌护盾'};
// 云开发环境 ID：在微信开发者工具“云开发”面板顶部复制，不是 AppID。
const CLOUD_ENV_ID='请替换为你的云环境ID';
if(wx.cloud&&CLOUD_ENV_ID.indexOf('请替换')!==0)wx.cloud.init({env:CLOUD_ENV_ID});
// 图片优先读取项目内 assets 目录，避免小游戏运行环境访问外部 CDN 超时。
// assets 目录随小游戏一起上传，不依赖浏览器代理、DNS 或 HTTP/2。
const LOCAL_ASSET_BASE='assets/';
// 真机兼容性优先：小游戏运行资源使用 PNG，避免部分设备对 WebP 编码解码失败。
const LOCAL_ASSET_EXT='png';
// 仅作为显式开启时的备用地址；默认关闭，避免启动时产生外网请求。
const REMOTE_ASSET_BASE='https://raw.githubusercontent.com/longqingxuexin/fish_game/main/public/img/';
const REMOTE_ASSET_EXT='webp';
const USE_REMOTE_ASSET_FALLBACK=false;
const ASSET_FILES={};
const CLOUD_ASSET_FILES={
  // 示例：bg0:'cloud://环境ID.存储桶ID/鱼游戏/bg0.png'
};
const imageCache={};
const imageState={};
const downloadedAssets={},preloadedImages={},customImageCache={};
const customImg=p=>{if(!p)return null;if(customImageCache[p])return customImageCache[p];const i=wx.createImage();i.src=p;customImageCache[p]=i;return i};
const CUSTOM_KEY='fish_custom_assets_v1';
const customTypes=[['player','自定义主角鱼'],['small','自定义小鱼'],['big','自定义大鱼'],['boss','自定义Boss鱼'],['background','自定义背景图'],['global_eat','全屏吞噬特效'],['type_eat','同类吞噬特效'],['speed_up','极速冲刺特效'],['grow','巨型成长特效'],['heal','生命恢复特效'],['invincible','无敌护盾特效']];
const systemInfo=wx.getSystemInfoSync?wx.getSystemInfoSync():{};
const touchPoint=t=>{const rawX=t.clientX??t.pageX??t.x??0,rawY=t.clientY??t.pageY??t.y??0;const screenW=systemInfo.windowWidth||W,screenH=systemInfo.windowHeight||H;return{x:rawX*W/screenW,y:rawY*H/screenH}};
let customPage=false,customPreview=null;
const loadCustom=()=>{try{return wx.getStorageSync(CUSTOM_KEY)||{assets:[]}}catch(e){return{assets:[]}}};
const saveCustom=s=>wx.setStorageSync(CUSTOM_KEY,s);
const getCustom=type=>loadCustom().assets.find(a=>a.type===type);
const putCustom=a=>{const s=loadCustom();s.assets=[...s.assets.filter(x=>x.type!==a.type),a];saveCustom(s)};
const removeCustom=type=>{const s=loadCustom();s.assets=s.assets.filter(x=>x.type!==type);saveCustom(s)};
const adjustCustom=(type,field,delta)=>{const a=getCustom(type)||{type,frames:[]};if(field==='speed')a.speed=Math.max(1,Math.min(1000,(a.speed||40)+delta));if(field==='min'){a.durationMin=Math.max(0,Math.min(600,(a.durationMin??2)+delta));if(a.durationMax!==undefined&&a.durationMax<a.durationMin)a.durationMax=a.durationMin}if(field==='max'){a.durationMax=Math.max(a.durationMin??0,Math.min(600,(a.durationMax??4)+delta))}putCustom(a)};
const drawCustomSettings=()=>customTypes.forEach((t,i)=>{const a=getCustom(t[0])||{},y=78+i*52;ctx.fillStyle='#b8d9e8';ctx.font='10px sans-serif';if(['player','small','big','boss'].includes(t[0]))ctx.fillText(`游动速度:${a.speed??40}（点击左右调整）`,180,y+39);if(['global_eat','type_eat','speed_up','grow','heal','invincible'].includes(t[0]))ctx.fillText(`持续时间:${a.durationMin??2}-${a.durationMax??4}s（左右调整）`,180,y+39)});
wx.onTouchStart(e=>{if(!customPage||customPreview)return;const t=e.touches[0],{x,y}=touchPoint(t),i=Math.floor((y-78)/52),type=customTypes[i]?.[0];if(!type||x>=145||!getCustom(type))return;if(['player','small','big','boss'].includes(type))adjustCustom(type,'speed',x<70?-1:1);else if(x<38)adjustCustom(type,'min',-1);else if(x<72)adjustCustom(type,'min',1);else if(x<106)adjustCustom(type,'max',-1);else adjustCustom(type,'max',1)});
const isLight=(r,g,b)=>((r+g+b)/3>=145&&Math.max(r,g,b)-Math.min(r,g,b)<=55);
const processCustomImage=(path,type)=>new Promise((resolve,reject)=>{wx.getImageInfo({src:path,success:info=>{const c=wx.createOffscreenCanvas?wx.createOffscreenCanvas({type:'2d'}):wx.createCanvas();const scale=Math.min(1,1200/Math.max(info.width,info.height));c.width=Math.max(1,Math.round(info.width*scale));c.height=Math.max(1,Math.round(info.height*scale));const x=c.getContext('2d');const im=wx.createImage();im.onload=()=>{x.drawImage(im,0,0,c.width,c.height);if(type!=='background'){const d=x.getImageData(0,0,c.width,c.height),q=[],v=new Uint8Array(c.width*c.height),add=(a,b)=>q.push(b*c.width+a);for(let a=0;a<c.width;a++){add(a,0);add(a,c.height-1)}for(let b=0;b<c.height;b++){add(0,b);add(c.width-1,b)}for(let h=0;h<q.length;h++){const i=q[h];if(v[i])continue;v[i]=1;const o=i*4;if(d.data[o+3]===0||!isLight(d.data[o],d.data[o+1],d.data[o+2]))continue;d.data[o+3]=0;const a=i%c.width,b=Math.floor(i/c.width);if(a) add(a-1,b);if(a+1<c.width)add(a+1,b);if(b)add(a,b-1);if(b+1<c.height)add(a,b+1)}for(let i=0;i<d.data.length;i+=4){if(d.data[i+3]===0)d.data[i]=d.data[i+1]=d.data[i+2]=0;else if(d.data[i+3]<255&&Math.max(d.data[i],d.data[i+1],d.data[i+2])>=180)d.data[i+3]=0}x.putImageData(d,0,0)}wx.canvasToTempFilePath({canvas:c,fileType:'png',success:r=>wx.saveFile({tempFilePath:r.tempFilePath,success:s=>resolve(s.savedFilePath),fail:reject}),fail:reject})};im.onerror=reject;im.src=path},fail:reject})});
const uploadCustom=type=>wx.chooseImage({count:['global_eat','type_eat','speed_up','grow','heal','invincible'].includes(type)?9:1,sizeType:['original','compressed'],sourceType:['album','camera'],success:r=>Promise.all(r.tempFilePaths.map(p=>processCustomImage(p,type))).then(paths=>putCustom({type,frames:paths,speed:getCustom(type)?.speed,durationMin:getCustom(type)?.durationMin,durationMax:getCustom(type)?.durationMax})).catch(e=>console.warn('自定义图片处理失败',e))});
const ASSET_NAMES=[...['bg0','bg1','bg2','bg3'],...['fish_small_1','fish_small_2','fish_small_3','fish_small_4','fish_small_5'],...['fish_big_6','fish_big_7','fish_big_8','fish_big_9'],...['fish_boss_1','fish_boss_10','fish_boss_11','fish_boss_12'],...['player_0','player_1','player_2','player_3','player_4'],...['fx_global'],...[1,2,3,4].map(n=>`fx_type_${n}`),...[1,2,3,4].map(n=>`fx_speed_${n}`),...[1,2,3,4].map(n=>`fx_grow_${n}`),...[1,2,3].map(n=>`fx_heal_${n}`),...[1,2].map(n=>`fx_shield_${n}`)];
const loadLocalAsset=(name,url)=>new Promise(resolve=>{const i=wx.createImage();imageState[name]='loading';i.onload=()=>{preloadedImages[name]=i;downloadedAssets[name]=url;imageState[name]='loaded';resolve(true)};i.onerror=e=>{imageState[name]='failed';console.warn('本地图片加载失败',name,url,e);resolve(false)};i.src=url});
const downloadAsset=(name,attempt=0)=>{const fileId=CLOUD_ASSET_FILES[name],localUrl=`${LOCAL_ASSET_BASE}${name}.${LOCAL_ASSET_EXT}`;if(!fileId)return loadLocalAsset(name,localUrl).then(ok=>{if(ok||!USE_REMOTE_ASSET_FALLBACK)return ok;return new Promise(resolve=>wx.downloadFile({url:`${REMOTE_ASSET_BASE}${name}.${REMOTE_ASSET_EXT}`,success:r=>{if(r.statusCode===200){downloadedAssets[name]=r.tempFilePath;imageState[name]='loaded';resolve(true)}else resolve(false)},fail:e=>{console.warn('远程图片备用加载失败',name,e);resolve(false)}}))});return new Promise(resolve=>{const done=r=>{if(r.statusCode===200){downloadedAssets[name]=r.tempFilePath;imageState[name]='loaded';resolve(true)}else if(attempt<2)setTimeout(()=>resolve(downloadAsset(name,attempt+1)),300);else{imageState[name]='failed';resolve(false)}};const fail=e=>{if(attempt<2)setTimeout(()=>resolve(downloadAsset(name,attempt+1)),300);else{imageState[name]='failed';console.warn('云图片加载失败',name,e);resolve(false)}};if(wx.cloud)wx.cloud.downloadFile({fileID:fileId}).then(r=>done({statusCode:200,tempFilePath:r.tempFilePath})).catch(fail);else fail(new Error('wx.cloud unavailable'))})};
const preloadAssets=()=>Promise.all(ASSET_NAMES.map(n=>downloadAsset(n)));
const img=n=>{if(preloadedImages[n]){imageCache[n]=preloadedImages[n];return preloadedImages[n]}const i=wx.createImage();imageCache[n]=i;imageState[n]=imageState[n]||'loading';i.onload=()=>{imageState[n]='loaded'};i.onerror=e=>{imageState[n]='failed';console.warn('图片使用失败，使用绘制fallback',n,e)};i.src=downloadedAssets[n]||`${LOCAL_ASSET_BASE}${n}.${LOCAL_ASSET_EXT}`;return i};
let bg,small,big,boss,playerImgs,fx;
const initImages=()=>{bg=[0,1,2,3].map(n=>img(`bg${n}`));small=[1,2,3,4,5].map(n=>img(`fish_small_${n}`));big=[6,7,8,9].map(n=>img(`fish_big_${n}`));boss=[1,10,11,12].map(n=>img(`fish_boss_${n}`));playerImgs=[0,1,2,3,4].map(n=>img(`player_${n}`));fx={global_eat:[img('fx_global')],type_eat:[1,2,3,4].map(n=>img(`fx_type_${n}`)),speed_up:[1,2,3,4].map(n=>img(`fx_speed_${n}`)),grow:[1,2,3,4].map(n=>img(`fx_grow_${n}`)),heal:[1,2,3].map(n=>img(`fx_heal_${n}`)),invincible:[1,2].map(n=>img(`fx_shield_${n}`))}};
const rand=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);let player={x:W/2,y:H/2,size:20},fishes=[],skill,effect,particles=[],score=0,health=3,last,running=false,bgIndex=0,nextSkillAt,startedAt,growthXp,growthLevel,bossSpawned,screen='loading',savedSize=20,maxFishCount=6,endless=false;
function viewScale(){return Math.min(1,(W*.20)/(player.size*2))}function displaySize(s){return Math.max(3,s*viewScale())}
function makeFish(forceSize=0,isBoss=false){const min=Math.max(1,player.size*.1-1),max=Math.max(min+1,player.size*1.1),size=forceSize||rand(min,max),type=isBoss?'boss':size>48?'big':'small',custom=getCustom(type),x=rand(12,W-12),y=rand(100,H-14),tx=player.x-x,ty=player.y-y,d=Math.hypot(tx,ty)||1;return{x,y,size,kind:Math.floor(rand(0,5)),dx:size>player.size?tx/d:Math.random()<.5?-1:1,dy:size>player.size?ty/d:rand(-.35,.35),speed:custom?.speed||(isBoss?rand(10,18):rand(28,68)),phase:Math.random()*Math.PI*2,turn:0,isBoss,type}}
function reset(inherit=false){const size=inherit?Math.max(20,savedSize):20;player={x:W/2,y:H/2,size,targetX:W/2,targetY:H/2};maxFishCount=6+Math.floor(Math.random()*10);fishes=Array.from({length:maxFishCount},makeFish);skill=null;effect=null;particles=[];score=0;health=3;growthXp=0;growthLevel=inherit?Math.min(4,Math.max(0,Math.floor((size-20)/8))):0;bossSpawned=false;startedAt=Date.now();running=true;screen='playing';nextSkillAt=Date.now()+5000;bgIndex=(bgIndex+1)%Math.max(1,bg.length)}
function burst(color,count=18){for(let i=0;i<count;i++)particles.push({x:player.x,y:player.y,dx:rand(-130,130),dy:rand(-130,130),life:1,color})}
function spawnSkill(){const types=Object.keys(skillNames);skill={x:rand(35,W-35),y:rand(120,H-50),size:20,type:types[Math.floor(rand(0,types.length))]}}
function startSkill(){const type=skill.type,base={global_eat:4,type_eat:3,speed_up:3,grow:2,heal:2,invincible:4},a=getCustom(type),min=a?.durationMin??base[type],max=a?.durationMax??min,duration=min+Math.random()*Math.max(0,max-min);effect={type,started:Date.now(),until:Date.now()+duration*1000,acc:0};skill=null;burst(type==='heal'?'#7dff9b':'#ffe66d',35);if(type==='grow')player.size+=player.size*.18;if(type==='heal')health=Math.min(3,health+1)}
function eatFish(i){const f=fishes[i];const ratio=f.size/player.size;const xp=ratio>=.82?3.2:ratio>=.58?2:ratio>=.35?1:.45;growthXp+=xp;score+=Math.round(f.size*10);const threshold=8+growthLevel*4;if(growthLevel<4&&growthXp>=threshold){growthXp-=threshold;growthLevel++;player.size=Math.min(92,player.size+6+growthLevel*2);burst('#ffe66d',24)}else{player.size=Math.min(92,player.size+Math.max(1,Math.min(2.4,Math.max(.25,f.size/player.size*1.4))))}fishes.splice(i,1);fishes.push(makeFish());burst('#fff',5)}
function maybeSpawnBoss(){if(bossSpawned||Date.now()-startedAt<300000&&growthLevel<4)return;bossSpawned=true;const bossSize=Math.max(78,player.size*1.28);fishes.push(makeFish(bossSize,true));}
function activeEat(dt){if(!effect)return;effect.acc+=dt;if(effect.acc<.08)return;effect.acc=0;const radius=effect.type==='global_eat'?240:effect.type==='type_eat'?130:70;for(const f of fishes){const same=effect.type!=='type_eat'||f.kind===Math.floor(player.size)%5;if(dist(player,f)<radius&&f.size<player.size&&same)f.attracted=true}}
function update(dt){const speed=effect?.type==='speed_up'?420:360,dx=player.targetX-player.x,dy=player.targetY-player.y,d=Math.hypot(dx,dy)||1;player.x+=dx*Math.min(1,dt*18);player.y+=dy*Math.min(1,dt*18);if(d>3){player.dx=dx/d;player.dy=dy/d}fishes.forEach(f=>{if(f.attracted){const mouth={x:player.x+displaySize(player.size)*.9,y:player.y},mx=mouth.x-f.x,my=mouth.y-f.y,md=Math.hypot(mx,my)||1;f.x+=mx/md*Math.max(180,md*4)*dt;f.y+=my/md*Math.max(180,md*4)*dt;f.phase+=dt*12;return}f.x+=f.dx*f.speed*dt;f.y+=f.dy*f.speed*dt;f.phase+=dt*(4+f.speed*.04);f.turn+=dt;if(f.turn>rand(.8,1.8)){f.dy=rand(-.3,.3);f.turn=0}if(f.x<-50||f.x>W+50)f.dx*=-1;if(f.y<85||f.y>H-8)f.dy*=-1});maybeSpawnBoss();for(let i=fishes.length-1;i>=0;i--){const f=fishes[i];if(f.attracted){if(dist({x:player.x+displaySize(player.size)*.9,y:player.y},f)<Math.max(12,displaySize(player.size)*.35))eatFish(i);continue}if(dist(player,f)<displaySize(player.size)+displaySize(f.size)){if(player.size>=f.size)eatFish(i);else if(f.size>player.size*1.05&&effect?.type!=='invincible'){health--;fishes.splice(i,1);fishes.push(makeFish());if(health<=0)running=false}}}if(Date.now()>=nextSkillAt){spawnSkill();nextSkillAt=Date.now()+5000}if(skill&&dist(player,skill)<displaySize(player.size)+skill.size)startSkill();if(effect){activeEat(dt);if(Date.now()>=effect.until){fishes.forEach(f=>f.attracted=false);effect=null}}particles.forEach(p=>{p.x+=p.dx*dt;p.y+=p.dy*dt;p.life-=dt*1.7});particles=particles.filter(p=>p.life>0)}
function drawFallback(x,y,w,h,color='#55cbe8',r=0){ctx.save();ctx.translate(x,y);ctx.rotate(r);ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(0,0,w*.36,h*.22,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-w*.25,0);ctx.lineTo(-w*.52,-h*.25);ctx.lineTo(-w*.52,h*.25);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(w*.18,-h*.06,Math.max(2,w*.035),0,Math.PI*2);ctx.fill();ctx.restore()}
function drawImg(i,x,y,w,h,a=1,r=0){if(!i||!i.width){drawFallback(x,y,w,h,'#55cbe8',r);return}ctx.save();ctx.globalAlpha=a;ctx.translate(x,y);ctx.rotate(r);ctx.drawImage(i,-w/2,-h/2,w,h);ctx.restore()}
function drawFish(f,isPlayer=false){const minRenderSize=isPlayer?48:f.isBoss?72:f.size>48?46:18,s0=Math.max(minRenderSize,displaySize(f.size)*2.7),d=isPlayer||!f.attracted?1:Math.max(.15,Math.min(1,dist(player,f)/(displaySize(player.size)*3))),s=s0*d,custom=isPlayer?getCustom('player'):getCustom(f.type),arr=isPlayer?playerImgs:f.isBoss?boss:f.size>48?big:small,playerStage=[1,2,3,4,0],i=arr[isPlayer?playerStage[Math.min(4,growthLevel)]:f.kind%arr.length],angle=(f.dy||0)*.18+Math.sin(f.phase||0)*.025;ctx.save();ctx.translate(f.x,f.y+Math.sin(f.phase||0)*1.2);ctx.globalAlpha=isPlayer||!f.attracted?1:Math.min(1,dist(player,f)/35);if(f.dx<0&&!isPlayer)ctx.scale(-1,1);if(custom?.frames?.length){const ci=customImg(custom.frames[0]);if(ci?.width)ctx.drawImage(ci,-s/2,-s/2,s,s);else drawImg(i,0,0,s,s,1,angle)}else drawImg(i,0,0,s,s,1,angle);ctx.restore();if(!f.attracted){ctx.fillStyle=f.isBoss?'#ffe66d':'#fff';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText(Math.round(f.size),f.x,f.y-s*.46);ctx.textAlign='left'}}
function drawCustomPage(){ctx.fillStyle='#061b33';ctx.fillRect(0,0,W,H);ctx.fillStyle='#eaffff';ctx.font='bold 22px sans-serif';ctx.fillText('自定义资源',18,34);ctx.font='14px sans-serif';ctx.fillText('点击上传；预览/删除在每行右侧',18,58);ctx.fillStyle='#087f9d';ctx.fillRect(W-108,18,90,34);ctx.fillStyle='#fff';ctx.fillText('完成返回',W-96,40);customTypes.forEach((t,i)=>{const y=78+i*52,a=getCustom(t[0]);ctx.fillStyle='rgba(9,48,75,.9)';ctx.fillRect(10,y,W-20,44);ctx.fillStyle='#fff';ctx.fillText(t[1],18,y+27);ctx.fillStyle='#7de3ff';ctx.fillText(a?`${a.frames.length}帧`:'未设置',145,y+27);ctx.fillStyle='#1254a4';ctx.fillRect(W-175,y+6,48,32);ctx.fillRect(W-120,y+6,48,32);ctx.fillStyle='#fff';ctx.fillText('上传',W-165,y+27);ctx.fillText('预览',W-112,y+27);if(a){ctx.fillStyle='#d85b66';ctx.fillRect(W-64,y+6,48,32);ctx.fillStyle='#fff';ctx.fillText('删除',W-57,y+27)}});if(customPreview){const a=getCustom(customPreview.type),p=a?.frames?.[Math.floor(Date.now()/120)%(a?.frames?.length||1)],i=p&&customImg(p);ctx.fillStyle='rgba(0,0,0,.8)';ctx.fillRect(20,100,W-40,H-140);if(i?.width)ctx.drawImage(i,45,135,W-90,H-210);ctx.fillStyle='#fff';ctx.fillText('点击任意位置关闭预览',W/2-75,H-58)}}
function draw(){if(customPage){drawCustomPage();return}const customBg=getCustom('background');if(customBg?.frames[0]){const b=customImg(customBg.frames[0]);if(b?.width)ctx.drawImage(b,0,0,W,H);else drawImg(bg[bgIndex],W/2,H/2,W,H)}else drawImg(bg[bgIndex],W/2,H/2,W,H);ctx.fillStyle='rgba(1,20,42,.82)';ctx.fillRect(0,0,W,76);ctx.fillStyle='#eaffff';ctx.font='bold 18px sans-serif';ctx.fillText('吃鱼泡泡',16,29);ctx.font='14px sans-serif';ctx.fillText(`分数 ${score} 生命 ${health} 体型 ${Math.round(player.size)} 成长 ${growthLevel}/4`,16,54);fishes.forEach(f=>drawFish(f));if(skill){drawImg(fx[skill.type][0],skill.x,skill.y,skill.size*4,skill.size*4,.9,Date.now()/1000);ctx.fillStyle='#fff';ctx.fillText(skillNames[skill.type],skill.x-24,skill.y+35)}particles.forEach(p=>{ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1});drawFish(player,true);if(effect?.type==='global_eat'){const t=Date.now()/300,r=displaySize(player.size)*(2.3+Math.sin(t)*.2);ctx.strokeStyle='rgba(255,230,109,.85)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(player.x,player.y,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#fff0a0';for(let i=0;i<10;i++){const a=t+i*.628;ctx.beginPath();ctx.arc(player.x+Math.cos(a)*r*.72,player.y+Math.sin(a)*r*.72,2.5,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#fff';ctx.font='bold 16px sans-serif';ctx.fillText('吸',player.x+displaySize(player.size)*.75,player.y-displaySize(player.size)*.8)}if(effect){const frames=fx[effect.type],frame=Math.floor(Date.now()/100)%frames.length,s=displaySize(player.size)*3;drawImg(frames[frame],player.x,player.y,s,s,.55,Date.now()/2600)}if(!running){ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 30px sans-serif';ctx.fillText('游戏结束',W/2,H/2);ctx.textAlign='left'}}
function drawMenu(){if(screen==='playing')return;ctx.fillStyle='rgba(1,20,42,.88)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#eaffff';ctx.textAlign='center';ctx.font='bold 30px sans-serif';ctx.fillText('吃鱼泡泡',W/2,170);ctx.font='16px sans-serif';ctx.fillText(screen==='loading'?'正在加载海底世界…':screen==='leaderboard'?'TOP 5 排行榜':'新的开始 / 重新开始',W/2,215);if(screen==='leaderboard')(wx.getStorageSync('fish_leaderboard')||[]).forEach((r,i)=>ctx.fillText(`${i+1}. ${r.score} 分 · 体型 ${r.size}`,W/2,260+i*30));ctx.textAlign='left'}
function drawMenuButtons(){if(screen!=='menu'||customPage)return;ctx.fillStyle='#087f9d';ctx.fillRect(55,330,265,48);ctx.fillStyle='#1254a4';ctx.fillRect(55,390,265,48);ctx.fillStyle='#176b82';ctx.fillRect(55,450,265,48);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 18px sans-serif';ctx.fillText('新的开始',W/2,361);ctx.fillText('重新开始',W/2,421);ctx.fillText('自定义',W/2,481);ctx.font='14px sans-serif';ctx.fillText('排行榜（左下角）',W/2,530);ctx.textAlign='left'}
function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(running)update(dt);if(!running&&screen==='playing'){screen='gameover';savedSize=player.size;const ranks=wx.getStorageSync('fish_leaderboard')||[];ranks.push({score,size:Math.round(player.size),createdAt:Date.now()});ranks.sort((a,b)=>b.score-a.score);wx.setStorageSync('fish_leaderboard',ranks.slice(0,5))}draw();if(customPage)drawCustomSettings();if(!customPage){drawMenu();drawMenuButtons()}requestAnimationFrame(loop)}
wx.onTouchStart(e=>{const t=e.touches[0],{x,y}=touchPoint(t);if(customPage){if(customPreview){customPreview=null;return}if(y<65){customPage=false;screen='menu';saveCustom(loadCustom());return}const i=Math.floor((y-78)/52);if(i<0||i>=customTypes.length)return;const type=customTypes[i][0];if(x>W-180&&x<W-125){uploadCustom(type);return}if(x>W-125&&x<W-72){if(getCustom(type)?.frames?.length)customPreview={type,index:0};return}if(x>W-72){removeCustom(type);return}return}if(screen==='leaderboard'||screen==='gameover'){screen='menu';running=false;return}if(screen==='menu'){if(y>=450&&y<500){customPage=true;running=false;return}if(y>500){screen='leaderboard';return}if(y>=330&&y<385){reset(false);return}if(y>=385&&y<445){reset(true);return}return}if(screen==='loading')return;player.targetX=x;player.targetY=y});wx.onTouchMove(e=>{if(screen!=='playing')return;const {x,y}=touchPoint(e.touches[0]);player.targetX=Math.max(8,Math.min(W-8,x));player.targetY=Math.max(85,Math.min(H-8,y))});
// 预加载本地打包资源，弱网环境下不依赖外部 CDN。
preloadAssets().then(()=>{initImages();screen='menu';requestAnimationFrame(now=>{last=now;loop(now)})});
wx.onTouchStart(e=>{if(!customPage||customPreview)return;const t=e.touches[0],{x,y}=touchPoint(t),i=Math.floor((y-78)/52),type=customTypes[i]?.[0];if(!type||x>=145||getCustom(type))return;if(['player','small','big','boss'].includes(type))adjustCustom(type,'speed',x<70?-1:1);else if(x<38)adjustCustom(type,'min',-1);else if(x<72)adjustCustom(type,'min',1);else if(x<106)adjustCustom(type,'max',-1);else adjustCustom(type,'max',1)});
// 微信端无尽挑战入口：菜单第五个区域启动 10 分钟挑战；普通模式逻辑保持不变。
wx.onTouchStart(e=>{if(customPage||screen!=='menu')return;const {y}=touchPoint(e.touches[0]);if(y>=445&&y<500){endless=true;reset(false);}});
setInterval(()=>{if(!endless||screen!=='playing')return;const seconds=(Date.now()-startedAt)/1000;if(seconds>=600){running=false;endless=false;screen='gameover'}else if(!bossSpawned&&seconds>=300){bossSpawned=true;fishes.push(makeFish(Math.max(78,player.size*1.28),true));}},1000);
wx.onTouchStart(e=>{if(customPage||screen!=='menu')return;const {y}=touchPoint(e.touches[0]);if(y>=330&&y<445)endless=false;});
