import './style.css';
import { SaveManager } from './core/save-manager';
import { addFiles, CUSTOM_TYPES, getCustom, loadCustom, removeCustom, saveCustom, CustomAsset } from './customization';

type Screen = 'loading'|'menu'|'playing'|'leaderboard'|'gameover';
type Rank = { score:number; size:number; createdAt:number };
const canvas=document.querySelector<HTMLCanvasElement>('#game')!,ctx=canvas.getContext('2d')!,W=canvas.width,H=canvas.height;
const stats=document.querySelector('#stats')!,message=document.querySelector('#message')!,saveManager=new SaveManager();
const customPage=document.querySelector<HTMLElement>('#custom-page')!,customList=document.querySelector('#custom-list')!;
const modal=document.querySelector<HTMLElement>('#preview-modal')!,previewImage=document.querySelector<HTMLImageElement>('#preview-image')!,previewTitle=document.querySelector('#preview-title')!;
const bgNames=['bg0.webp','bg1.webp','bg2.webp','bg3.webp'],cache=new Map<string,HTMLImageElement>();
let screen:Screen='loading',running=false,score=0,playerSize=22,maxScore=0,health=3,coins=0,px=W/2,py=H/2,last=0;
const playerStageAsset=()=>playerSize>=78?'player_0.webp':playerSize>=58?'player_4.webp':playerSize>=42?'player_3.webp':playerSize>=30?'player_2.webp':'player_1.webp';
let fishes:{x:number;y:number;s:number;dx:number;dy:number;type:string;asset?:CustomAsset}[]=[];
let activeSkill: { type:string; until:number }|null=null;
let skillOrb: { type:string; x:number; y:number }|null=null, nextSkillAt=0;
const image=(src:string)=>{let i=cache.get(src);if(i)return i;i=new Image();i.src=src.startsWith('data:')?src:'/img/'+src;cache.set(src,i);return i};
const ranks=():Rank[]=>{try{return JSON.parse(localStorage.getItem('fish_leaderboard')||'[]')}catch{return []}};
function record(){localStorage.setItem('fish_leaderboard',JSON.stringify([...ranks(),{score,size:Math.round(playerSize),createdAt:Date.now()}].sort((a,b)=>b.score-a.score).slice(0,5)))}
function drawImg(src:string,x:number,y:number,w:number,h:number,alpha=1){const i=image(src);if(i.complete&&i.naturalWidth){ctx.globalAlpha=alpha;ctx.drawImage(i,x-w/2,y-h/2,w,h);ctx.globalAlpha=1}}
function fallback(){ctx.fillStyle='#082d50';ctx.fillRect(0,0,W,H);for(let i=0;i<24;i++){ctx.fillStyle='rgba(100,220,255,.2)';ctx.beginPath();ctx.arc((i*83)%W,90+(i*57)%H,3+i%4,0,Math.PI*2);ctx.fill()}}
function drawMenu(){ctx.fillStyle='rgba(2,18,42,.84)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#eaffff';ctx.textAlign='center';ctx.font='bold 42px sans-serif';ctx.fillText('吃鱼泡泡',W/2,155);ctx.font='18px sans-serif';ctx.fillText(screen==='loading'?'正在加载海底世界…':screen==='leaderboard'?'TOP 5 排行榜':'准备好成为海底霸主了吗？',W/2,205);if(screen==='leaderboard')ranks().forEach((r,i)=>ctx.fillText(`${i+1}. ${r.score} 分 · 体型 ${r.size}`,W/2,260+i*34));ctx.textAlign='left'}
function draw(){ctx.clearRect(0,0,W,H);const customBg=getCustom('background')?.frames[0]?.dataUrl;if(customBg)drawImg(customBg,W/2,H/2,W,H);else{const b=image(bgNames[0]);if(b.complete&&b.naturalWidth)ctx.drawImage(b,0,0,W,H);else fallback()}if(screen!=='playing'&&screen!=='gameover'){drawMenu();stats.textContent=screen==='leaderboard'?'本地最高分记录':'请选择开始方式';return}ctx.fillStyle='rgba(0,20,42,.72)';ctx.fillRect(0,0,W,76);ctx.fillStyle='#fff';ctx.font='bold 18px sans-serif';ctx.fillText('吃鱼泡泡',16,29);ctx.font='14px sans-serif';ctx.fillText(`分数 ${score}  生命 ${health}  体型 ${Math.round(playerSize)}`,16,54);for(const f of fishes){const src=f.asset?.frames[0]?.dataUrl||(f.type==='big'?'fish_big_8.webp':f.type==='boss'?'fish_boss_1.webp':'fish_small_2.webp');drawImg(src,f.x,f.y,Math.max(34,f.s*2),Math.max(25,f.s),.95);ctx.fillStyle='#fff';ctx.fillText(String(Math.round(f.s)),f.x-8,f.y-f.s)}if(skillOrb){ctx.fillStyle='#ffe66d';ctx.beginPath();ctx.arc(skillOrb.x,skillOrb.y,22,0,Math.PI*2);ctx.fill();ctx.fillStyle='#17324a';ctx.font='bold 12px sans-serif';ctx.fillText('技',skillOrb.x-7,skillOrb.y+5)}const p=getCustom('player')?.frames[0]?.dataUrl||playerStageAsset();drawImg(p,px,py,playerSize*2,playerSize*2);if(activeSkill){const effect=getCustom(activeSkill.type)?.frames;const frame=effect?.[Math.floor(Date.now()/120)%effect.length]?.dataUrl;if(frame)drawImg(frame,px,py,playerSize*4,playerSize*4,.78);else{ctx.strokeStyle='#ffe66d';ctx.lineWidth=5;ctx.beginPath();ctx.arc(px,py,playerSize*1.8,0,Math.PI*2);ctx.stroke()}}stats.textContent=`分数 ${score} · 生命 ${health} · 体型 ${Math.round(playerSize)} · 最高分 ${maxScore}`;if(screen==='gameover'){ctx.fillStyle='rgba(0,0,0,.65)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 36px sans-serif';ctx.fillText('游戏结束',W/2,245);ctx.textAlign='left'}}
function makeFish():typeof fishes[number]{const customTypes=['small','big','boss'].filter(type=>getCustom(type));const type=customTypes.length&&Math.random()<.25?customTypes[Math.floor(Math.random()*customTypes.length)]:(Math.random()<.7?'small':'big'),s=type==='boss'?70:type==='big'?35+Math.random()*18:8+Math.random()*22;return{x:20+Math.random()*(W-40),y:90+Math.random()*(H-110),s,dx:Math.random()<.5?-1:1,dy:(Math.random()-.5)*.5,type,asset:getCustom(type)}}
function start(inherit:boolean){saveCustom(loadCustom());score=0;health=3;coins=0;playerSize=inherit?Math.max(22,playerSize):22;px=W/2;py=H/2;fishes=Array.from({length:24},makeFish);activeSkill=null;skillOrb=null;nextSkillAt=Date.now()+30000;screen='playing';running=true;message.textContent='拖动屏幕控制鱼移动；吞噬比自己小的鱼';requestAnimationFrame(loop)}
function update(dt:number){for(let i=fishes.length-1;i>=0;i--){const f=fishes[i],speed=getCustom(f.type)?.speed??(18+f.s);f.x+=f.dx*speed*dt;f.y+=f.dy*speed*dt;if(f.x<0||f.x>W)f.dx*=-1;if(f.y<85||f.y>H)f.dy*=-1;if(Math.hypot(f.x-px,f.y-py)<playerSize+f.s/2){if(playerSize>f.s*1.08){score+=Math.round(f.s*10);playerSize=Math.min(90,playerSize+f.s*.035);fishes.splice(i,1);fishes.push(makeFish())}else if(f.s>playerSize*1.15&&activeSkill?.type!=='invincible'){health--;fishes.splice(i,1);if(health<=0){running=false;screen='gameover';maxScore=Math.max(maxScore,score);record();message.textContent='游戏结束，点击画面返回主菜单'}}}}if(!skillOrb&&Date.now()>=nextSkillAt){const types=['global_eat','type_eat','speed_up','grow','heal','invincible'];skillOrb={type:types[Math.floor(Math.random()*types.length)],x:50+Math.random()*(W-100),y:110+Math.random()*(H-150)};nextSkillAt=Date.now()+30000}if(skillOrb&&Math.hypot(skillOrb.x-px,skillOrb.y-py)<playerSize+24){const a=getCustom(skillOrb.type),min=a?.durationMin??2,max=a?.durationMax??(a?.durationMin??4);activeSkill={type:skillOrb.type,until:Date.now()+(min+Math.random()*Math.max(0,max-min))*1000};skillOrb=null}px=Math.max(playerSize,Math.min(W-playerSize,px));py=Math.max(76+playerSize,Math.min(H-playerSize,py));if(activeSkill&&Date.now()>=activeSkill.until)activeSkill=null}
function loop(t:number){if(!running)return;const dt=Math.min(.05,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
/* legacy duplicate removed; the complete implementation below is the single page renderer */
function openCustom(){running=false;customPage.hidden=false;canvas.hidden=true;renderCustomPage()}function closeCustom(){saveCustom(loadCustom());customPage.hidden=true;canvas.hidden=false;screen='menu';draw()}
document.querySelector('#new-game')!.addEventListener('click',()=>start(false));document.querySelector('#resume-game')!.addEventListener('click',()=>start(true));document.querySelector('#customize')!.addEventListener('click',openCustom);document.querySelector('#custom-close')!.addEventListener('click',closeCustom);document.querySelector('#preview-close')!.addEventListener('click',()=>modal.hidden=true);modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true});document.querySelector('#leaderboard')!.addEventListener('click',()=>{running=false;screen='leaderboard';draw()});document.querySelector('#save')!.addEventListener('click',()=>saveManager.save({score,size:playerSize,maxScore:Math.max(maxScore,score),health,coins,savedAt:Date.now()}).then(()=>message.textContent='已保存'));document.querySelector('#load')!.addEventListener('click',()=>saveManager.load().then(d=>{if(d){score=d.score;playerSize=d.size;maxScore=d.maxScore;health=d.health;coins=d.coins;message.textContent='已读取存档'}}));canvas.addEventListener('pointermove',e=>{if(screen!=='playing')return;const r=canvas.getBoundingClientRect();px=(e.clientX-r.left)*W/r.width;py=(e.clientY-r.top)*H/r.height});canvas.addEventListener('pointerdown',()=>{if(screen==='gameover'||screen==='leaderboard'){screen='menu';draw()}});draw();screen='menu';message.textContent='请选择开始方式';draw();
function renderCustomPage(){const state=loadCustom();customList.innerHTML='';CUSTOM_TYPES.forEach(([type,label])=>{const item=document.createElement('article');item.className='custom-item';const current=state.assets.find(a=>a.type===type),multi=['global_eat','type_eat','speed_up','grow','heal','invincible'].includes(type),isSpeed=['player','small','big','boss'].includes(type),speed=current?.speed??40,min=current?.durationMin??2,max=current?.durationMax??(multi?4:2);item.innerHTML=`<strong>${label}</strong><div class="upload-box"><input type="file" accept="image/*" ${multi?'multiple':''}/><small>${multi?'可多选图片，按选择顺序播放':'单张图片'}</small></div><img alt="${label}预览"/><div><button class="preview">预览</button><button class="delete">删除</button><small class="frame-count">${current?.frames.length??0} 帧</small>${isSpeed?`<label class="setting-label">游动速度 <output class="speed-value">${speed}</output><input class="speed" type="range" min="1" max="1000" value="${speed}"/></label>`:''}${multi?`<label class="setting-label">持续时间范围 <output class="duration-value">${min}-${max} 秒</output><input class="min" type="range" min="0" max="600" value="${min}"/><input class="max" type="range" min="0" max="600" value="${max}"/></label>`:''}</div>`;const img=item.querySelector('img')!,count=item.querySelector('.frame-count')!;if(current?.frames[0])img.src=current.frames[0].dataUrl;item.querySelector('input[type=file]')!.addEventListener('change',async e=>{const files=(e.target as HTMLInputElement).files;if(!files?.length)return;const result=await addFiles(type,files);img.src=result.frames[0].dataUrl;count.textContent=`${result.frames.length} 帧`});['speed','min','max'].forEach(cls=>item.querySelector<HTMLInputElement>(`.${cls}`)?.addEventListener('input',()=>{const s=loadCustom(),a=s.assets.find(x=>x.type===type)||{type,frames:[]};const value=Number(item.querySelector<HTMLInputElement>(`.${cls}`)!.value);if(cls==='speed')a.speed=value;if(cls==='min')a.durationMin=value;if(cls==='max')a.durationMax=Math.max(a.durationMin??0,value);s.assets=[...s.assets.filter(x=>x.type!==type),a];saveCustom(s);const out=item.querySelector(cls==='speed'?'.speed-value':'.duration-value');if(out)out.textContent=cls==='speed'?String(a.speed):`${a.durationMin??min}-${a.durationMax??max} 秒`;}));customList.appendChild(item)})}
customList.addEventListener('click',e=>{const target=e.target as HTMLElement;if(!target.classList.contains('preview'))return;const item=target.closest('.custom-item');const index=Array.from(customList.children).indexOf(item as Element);const [type,label]=CUSTOM_TYPES[index]||[];const a=type&&getCustom(type);if(!a?.frames.length){message.textContent='请先上传图片后再预览';return}previewTitle.textContent=label;modal.hidden=false;let n=0;const tick=()=>{if(modal.hidden)return;previewImage.src=a.frames[n++%a.frames.length].dataUrl;if(a.frames.length>1)setTimeout(tick,120)};tick()});
